db:
  user: DB_USER
  password: DB_PASSWORD
  name: DB_NAME

session:
  app_key: SESSION_APP_KEY

email:
  mailgun_apikey: MAILGUN_APIKEY
  mailgun_domain: MAILGUN_DOMAIN

aws:
  key_id: AWS_KEY_ID
  key_secret: AWS_KEY_SECRET

google_oauth:
  client_id: GOOGLE_CLIENT_ID
  client_secret: GOOGLE_CLIENT_SECRET

github_oauth:
  client_id: GITHUB_CLIENT_ID
  client_secret: GITHUB_CLIENT_SECRET